api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json','application/merge-patch+json;version1.0','application/merge-patch+json;version1.1']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
        versions: [3]
    http_cache:
        invalidation:
            enabled: true
            # varnish_urls: ['%env(VARNISH_URL)%']
        public: true
    defaults:
        url_generation_strategy: !php/const ApiPlatform\Core\Api\UrlGeneratorInterface::ABS_URL
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
        


                
    
